# https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'

name: Test

jobs:
  check:
    name: Check (${{ matrix.features }})
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: [default, all]
    steps:
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v6
      - uses: actions-rs/cargo@v1
        with:
          command: check
          args: --workspace ${{ matrix.features == 'all' && '--all-features' || '' }}

  test:
    name: Test Suite (${{ matrix.features }})
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        features: [default, all]
    steps:
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler libprotobuf-dev
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: actions/checkout@v6
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace ${{ matrix.features == 'all' && '--all-features' || '' }}
